language: python
python:
  - "3.4"
# command to install dependencies
install: 
  - "pip install requests"
  - "pip install flask"
  - "pip install WTForms"
# command to run tests
script: "python testCases.py"